### ISSUE TITLE
Minimal, extended, and customized formats

### ISSUE THREAD

**Issue by prichterich** [Logiqx/open-gnss#1]
Here are some thoughts on formats for three different use cases: 
1. Routine speedsurfing (minimal)
2. Device tests (extended)
3. Everything else (customized). 

**Minimal format:**
The goal is the smallest possible file size. Contains only the data needed for speed analysis and track display that are currently in use, and omits all other items. This gives data records without compression. Simple differential compression of coordinates (suggested by Jan, date and time, and possibly other data can give further compression to less than 20 bytes per record. Data structures are predefined, headers are minimal.
Functionally, this format is similar to .sbp files.

**Device tests:**
This format contains additional data which can be useful when characterizing GPS devices, but not usually required for speed analysis and track display. Examples are various DOP numbers (HDOP, PDOP, etc.). 
Two options to implement this format are:
(a) Predefined and fixed (every file contains the same data items in every record).
(b) Defined in the header using pre-defined lookup tables for data items and types.
Functionally, this is somewhat similar to .ubx files.

**Customized format:**
This is a general format to support storing _any_ kind of data items in the file, as well as instructions on how to read the items (the data type). Functionally, this is similar to .fit files, and will borrow some ideas from fit files. However, it should be possible to define a format that is easier to understand and parse than FIT files. One example is that all record types present can be defined in the header. For each data item, meaning (e.g. "temperature"), data type (e.g. signed double) and units (e.g. "C") are defined. The "meaning" can either be a pre-defined meaning for common items, or a text description for uncommon items.
Functionally, this format is somewhat similar to FIT and XML (GPX) formats, and allows for the storage of anything. But in contrast to XML files, which depend on external descriptions of the data structures, the data format is described in the header.

One potential issue with the customized format is lack of uniformity: the use of different descriptions for the same data (like "cog" and "course" in GPX files). To address this, a consolidated dictionary of used terms, with extended descriptions, could be kept as part of the format description here. This is similar to the use of ontologies for DNA sequence annotation terms.

**Comment by Logiqx** [comment]
I think a lot of what you have said is captured in the "[thoughts and ideas](https://logiqx.github.io/open-gnss/thoughts.html)" page. All 3 use-cases can essentially be implemented in the same way, just with a different header or more specically, frame definition(s) which are shared by all GNSS frames.

Minimal format:
- I agree with the suggested fixed data content and that the frame structure should be prescribed. Personally, I think it should still use the same header system (specifically the frame definitions) as the other two use cases though. We can prescribe the content and logging devices generating the files can simply cut / paste the frame defintions into their software.
- The writer code would be simple but the reader code is exactly the same code for all other use-cases and doesn't rely upon hard-coded decisions that may change in the future. Lack of a header is at the cost of forward compatibility and would only save 36 bytes in total (4 bytes + 8 * 4 bytes = 36 bytes). Forward compatible is well worth 36 bytes.
- I'm not entirely sold on the delta idea for coordinates and timestamps. although it could easily be implemented in the system that I have proposed. There are plenty of values free for defining data types (7 of 16 currently used) so the frame definitions could easily support deltas. I'm just not entirely sure it's worthwhile to save a few bytes and we'd have to consider the impact of large deltas if the GNSS chip plays up. Perhaps you can do some analysis to ensure weird scenarios aren't present in existing files?

Device tests:
- I would definitely prefer option 2 as hard-coding / fixed formats will no doubt cause problems in the future. The minimal format only requires 36 bytes for the frame definitions so the device tests would likely by no more than 100 bytes. I don't see any real benefit in making such a format fixed because amongst other reasons it is very chipset dependent. Like the "minimal" use-case we can provide a "recipe" for u-blox device tests which is a simple cut/paste of pre-decided frame definitions. Frames can essentially be regarded as fixed by the logging device but file readers would treat them dynamically, using the same code as the other use-cases.

Customised:
- This is the use case that will most benefit from a dynamic fomat but as I've already discussed, I strongly feel this should be the same code as the other use cases but the other use cases have pre-agreed copy/pasted frame definitions.
- FIT files generally feel over-engineered to me and rather too flexible, leading to unnecessary complexity. I don't think we need to be nearly so flexible as we know what GNSS chips output and it is basically the precision that varies between suppliers.
- The potential issue that you picked up on (e.g. COG vs course) is one that I have tried to address during my draft format, making use of a fixed "dictionary" of items that can be referenced from frame definitions. To create a list of all of the items currently used by GP3S (lat, lon, cog, sog, etc) is a relatively small task and further additions can easily be made as and when it proves necessary (e.g. intertial measurements, compass, etc). Adding all of the "device test" and potential "custom" fields shouldn't be a biggie.
- It's the use of an official dictionary that will ensure that GPSResuilts, Speedreader, Gpsar know what to do with data items. The format that I proposed does however allow for different levels of endian / byte size / precsion from different devices. I feel this is of a great benefit because regardless of the unlreying chipset we can save "sog", "cog", "lat", "lon", etc. using the native prceission of the GNSS chip. The analysis software would just load it in and work with the precision provided. Well, I say "just" but once the development work is done it should work like a dream.

**Comment by Logiqx** [comment]
I have created conversation #20 to discuss "Format Complexity" and the topics in this issue. The opener is along the same lines as the ideas above but breaks the "customized" format down slightly, thus enabling conversations about distinct pieces of functionality. I have tried to avoid design or implementation details as much as possible.

@prichterich - If I have missed anything important or requiring discussion, please feel free to add it the conversation. I suggest this issue be closed once you have transferred any topics that I missed in the conversation opener.
